CREATE TABLE speakers
(
    speakerid SERIAL PRIMARY KEY,
    speaker_name VARCHAR(40),
    speaker_title VARCHAR(200),
    speaking_date VARCHAR(20),
    speaker_bio TEXT,
    speaker_image VARCHAR(60)
);

INSERT INTO speakers
    (speaker_name,
    speaker_title,
    speaking_date,
    speaker_bio,
    speaker_image)

VALUES
    ('Steve Rockwood', 'CEO of FamilySearch International', 'February 28', 'Stephen T. Rockwood is president and chief executive officer of FamilySearch International (www.FamilySearch.org). Rockwood, who most recently served as director of the international division at FamilySearch, became president and CEO on October 1, 2015. Prior to joining FamilySearch, Rockwood specialized in creating unique service offerings for worldwide customers of such brands as MasterCard International, AT&T, Disney, Office Depot, and Citibank among others. He was also a successful entrepreneur building two companies from the ground up that were later acquired by larger companies.', 'steverockwood.jpg'),
    ('Brandon Stanton', 'Humans of New York', 'March 1', 'Brandon Stanton studied at the University of Georgia and worked as a bond trader in Chicago before starting “Humans of New York”—a photography and storytelling blog—in the Summer of 2010. Over the course of seven years, HONY has built a devoted following of over 20 million fans on several social media platforms. He has appeared on Ellen, Good Morning America, Nightline, MSNBC, CNN, has been featured in The New York Times, The Wall Street Journal, The Los Angeles Times, Huffington Post, Mashable, and dozens of other media venues. He has also been named a ‘person of the week’ on the ABC Evening News with Diane Sawyer, and a Time Magazine “30 Under 30 Who are Changing the World,” and has photographed President Obama in the Oval Office. He has taken his work to some of the world''s most remote and troubled regions, and has used the storytelling power of his site to raise money for several life-changing altruistic purposes. He is the author of two #1 New York Times Bestsellers, HUMANS OF NEW YORK (2013) and HUMANS OF NEW YORK: STORIES (2015) and the Children’s book bestseller LITTLE HUMANS (2014).', 'brandon stanton.jpg'),
    ('Scott Hamilton', 'Olympic Gold Medalist', 'March 2', 'Scott Hamilton is the living example that good guys CAN finish first! He is an Olympic champion, cancer survivor, television broadcaster, motivational speaker, author, husband/father, and eternal optimist! During his figure skating career, Hamilton’s list of achievements include his Olympic gold medal, over 70 titles, awards, and honors. In 1990, Hamilton was inducted into the United States Olympic Hall of Fame, and in that same year he became a member of the World Figure Skating Hall of Fame. Following his mother’s passing from and his own survival of cancer, Hamilton launched the Scott Hamilton CARES Foundation (Cancer Alliance for Research, Education and Survivorship) in 2014, with a mission to improve cancer patient survivorship by supporting world class cancer research and the highest quality patient treatment and care. The same year, he founded the Scott Hamilton Skating Academy, in partnership with the NHL’s Nashville Predators, at Ford Ice Center in Antioch, TN, to offer students programs to help them fall in love with ice skating.', 'scott hamilton.jpg'),
    ('Henry Louis Gates, Jr', 'Alphonse Fletcher University Professor and Director of the Hutchins Center for African and African American Research at Harvard University', 'March 3', 'Henry Louis Gates, Jr. is the Alphonse Fletcher University Professor and Director of the Hutchins Center for African & African American Research at Harvard University. Emmy Award-winning filmmaker, literary scholar, journalist, cultural critic, and institution builder, Professor Gates has authored or co-authored twenty-two books and created eighteen documentary films, including Wonders of the African World, African American Lives, Faces of America, Black in Latin America, Black America since MLK: And Still I Rise, Africa’s Great Civilizations, and Finding Your Roots, his groundbreaking genealogy series now in its fourth season on PBS. His six-part PBS documentary series, The African Americans: Many Rivers to Cross (2013), which he wrote, executive produced, and hosted, earned the Emmy Award for Outstanding Historical Program—Long Form, as well as the Peabody Award, Alfred I. duPont-Columbia University Award, and NAACP Image Award.', 'henry louis gates.jpg'),
    ('Natalia Lafourcade', 'Mexican pop-rock singer and songwriter', 'March 3', 'Natalia Lafourcade is a Mexican pop-rock singer and songwriter who, since her debut in 2003, has been one of the most successful singers in the pop rock scene in Latin America. Natalia was born in Mexico City, Mexico, to musician parents. Her father is the Chilean musician Gastón Lafourcade, and her uncle is writer Enrique Lafourcade. She grew up in Coatepec, Veracruz, Mexico, where she studied music with her mother, María del Carmen Silva Contreras. In 2003, she was nominated for a Latin Grammy in the Best New Artist category for her debut album. Natalia has captured hearts all over Mexico and in countries across the world—Peru, Chile, Guatemala, Canada, Japan, the United States, Venezuela, Argentina, Spain, Italy, Dominican Republic, Colombia, and Denmark. Throughout her career, Natalia has received numerous honors and awards, including Grammy Awards and MTV Latino awards. Her undeniable talent and success are recognized from the Americas to Europe to Asia. She is an artist with charisma, a creator of contemporary music with immense appeal, and loyal to her musical heritage. Her audiences in all corners of the globe appreciate the simplicity and beauty of her interpretation. She is without a doubt an outstanding representative of the music of Mexico.', 'natalia Lafourcade.jpg');

;